### ISSUE TITLE
Job Failing With Syntax Error Using Upsert in Language-postrgesql

### ISSUE THREAD

**Issue by chaiwa-berian** [OpenFn/ret-international#1]
## Background, context, and business value

We are creating a demo job for the client which submits Kobotoolbox forms to Postgresql

## The specific request, in as few words as possible

The job is failing with the error below:
```
╭───────────────────────────────────────────────────────────────────╮
│ ◰ ◱ ◲ ◳  OpenFn/core ~ language-postgresql#v2.3.0 (Node v12.19.1) │
╰───────────────────────────────────────────────────────────────────╯
config: {
  
}
Preparing to upsert via: INSERT INTO beneficiary_registration (age, attachments, end_time, first_name, formhub_uuid, gender, geolocation, id, last_name, meta_instance_id, notes, services, start, status, submission_time, submitted_by, tags, uuid_column, validation_status, version, xform_id_string) VALUES [--REDACTED--]
        ON CONFLICT (formhub_uuid)
        DO UPDATE SET age=excluded.age, attachments=excluded.attachments, end_time=excluded.end_time, first_name=excluded.first_name, formhub_uuid=excluded.formhub_uuid, gender=excluded.gender, geolocation=excluded.geolocation, id=excluded.id, last_name=excluded.last_name, meta_instance_id=excluded.meta_instance_id, notes=excluded.notes, services=excluded.services, start=excluded.start, status=excluded.status, submission_time=excluded.submission_time, submitted_by=excluded.submitted_by, tags=excluded.tags, uuid_column=excluded.uuid_column, validation_status=excluded.validation_status, version=excluded.version, xform_id_string=excluded.xform_id_string;
Adding prepared SQL to state.queries array.
error: syntax error at or near ")"
    at Parser.parseErrorMessage (/home/app/priv/language_packs/language-postgresql-v2.3.0/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/app/priv/language_packs/language-postgresql-v2.3.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/app/priv/language_packs/language-postgresql-v2.3.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/app/priv/language_packs/language-postgresql-v2.3.0/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '289',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1145',
  routine: 'scanner_yyerror'
}
Unhandled error in the operations. Exiting process.
```
## To Reproduce
1. Here is a [link](https://openfn.org/projects/3023/jobs/3753) to a failed run on OpenFn.org 
### expression.js
[Link](https://github.com/OpenFn/ret-international/blob/master/jobs/expression.js) to the job itself in Github

### state.json

For the demo DB, see LP for `RET Demo Postgres DB`. 

Either provide state directly, or link to a file. If sensitive information
should be in state, redact it and provide instructions for where it can be
found.

```json
{
  "configuration": {
    
  },
  "data": {
    "__query_params": {},
    "body": {
      "Age": "25",
      "First_Name": "Felix",
      "Gender": "male",
      "Last_Name": "Phiri",
      "Services": "service_1 service_2 service_4",
      "__version__": "vwrdjsTYRoHAJxbZWnCcor",
      "_attachments": [],
      "_geolocation": [null, null],
      "_id": 75126512,
      "_notes": [],
      "_status": "submitted_via_web",
      "_submission_time": "2020-11-20T11:18:19",
      "_submitted_by": null,
      "_tags": [],
      "_uuid": "2e512959-7e18-476f-b420-96362fea69a1",
      "_validation_status": {},
      "_xform_id_string": "aMiEiFjejFkpRLuc3krcvp",
      "end": "2020-11-20T13:18:08.687+02:00",
      "formhub/uuid": "10f8e684befa4bd284ee05ff48dd62c8",
      "meta/instanceID": "uuid:2e512959-7e18-476f-b420-96362fea69a1",
      "start": "2020-11-20T13:17:28.494+02:00"
    },
    "form": "beneficiary_registration"
  }
}
```

## Expected behavior
It is expected to insert the record successfully or provide better logs with pointers to what might be causing the issue.

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (link) and confirming success.]

**Comment by aleksa-krolls** [comment]
@chaiwa-berian Can you please add the credentials for the Postgres database we're using for the demo to Last Pass? Create a new `Password`, enter in all configuration details, and share the Last Pass item with me... we want to make sure the Engineers can build the `configuration` to test locally. 

@taylordowns2000 Not sure if you have time to jump in here... I'd really like to unblock Chaiwa, but I don't want to slow down MF SMS development. See the run failure here (https://www.openfn.org/projects/3023/runs/10546855). Not sure what's happening - the syntax looks fine to me.
